Adds: Favorite Button to detail screen.
cs-daniel-lima/magicbyirineu pull request #108
Opened 2019-03-12 18:09 UTC by cs-andre-faruolo

- Favorite Button on Detail Screen responds to interaction and changes interface to correspond to it.
- Tests were written for it.

2019-03-12 18:19 UTC, cs-joao-souza requested changes

2019-03-12 18:19 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardDetail/View/CardDetailViewController.swift
> +            self.screen.favoriteButton.setAsNotFavorite()
Esse tipo de expressão foge a regra do `Law Of Demeter`

Vide [https://pt.wikipedia.org/wiki/Lei_de_Demeter#Vantagens](url).

Sugiro ter um método na screen que faça isso.

2019-03-12 18:19 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardDetail/View/FavoriteButton.swift
> +    var isFavorite: Bool
```suggestion
    private(set) var isFavorite: Bool
```

Se vc tem um método que faça o change pra vc, o ideal é que eu não possa alterar a variável de fora pois isso pode afetar o design da minha classe. Por exemplo, o método `setup(status: Bool)` faz alteração de appearance e título. Da forma que está eu posso alterar o `isFavorite` de fora para `true` e o estado que não é o estado verdadeiro da classe.

```suggestion
    var isFavorite: Bool {
          didSet {
               setup(status: isFavorite)
          }
    }
```

Sugiro remover o `setAsFavorite` e o `setAsNotFavorite` e criar um `setFavorite(isFavorite: Bool)`.

2019-03-12 19:03 UTC, cs-daniel-lima approved these changes

2019-03-12 19:26 UTC, cs-joao-souza requested changes

2019-03-12 19:26 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardDetail/View/FavoriteButton.swift
> +        switch isFavorite {
Esse switch é desnecessário.

`self.isFavorite = isFavorite`

2019-03-12 19:26 UTC, cs-joao-souza commented on magicbyirineuTests/Modules/CardDetail/CardDetailViewControllerSpec.swift
> +                sut.screen.favoriteButton.setFavorite(isFavorite: false)
Apesar de estar na classe de teste ainda continua violando a `Law of demeter`. 

Na minha opinião, deveria ter algo assim:

`screen.setFavorite(isFavorite: Bool)` futuramente se eu quiser mudar a forma de como  é favoritado eu teria que mudar as duas classes. Se eu tenho uma abstração de método dentro da VC eu só mudo em um lugar.

2019-03-13 12:55 UTC, cs-joao-souza approved these changes

2019-03-13 13:08 UTC, merged