Adds: Activity indicator in order to provide the user with an visual …
cs-daniel-lima/magicbyirineu pull request #114
Opened 2019-03-13 19:13 UTC by cs-andre-faruolo

…feedback on his query. Also implemented corresponding tests

2019-03-13 20:02 UTC, cs-joao-souza requested changes

2019-03-13 20:02 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
>              self.view.screen.collectionView.reloadData()
Isso aqui me assusta um pouco. Em tese isso deveria ser ação da view. Talvez ter algum método dentro da screen na qual vc possa fazer

`self.screen.reloadData()`

E dentro dele vc ter essa abstração.

2019-03-13 20:02 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/View/CardListView.swift
> +    var activityIndicator: UIActivityIndicatorView = {
aqui pode ser `let`.

2019-03-13 20:02 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/View/CardListView.swift
> +        case .normal:
Como vocês estão trabalhando com `State`. Não é plausível ter um State de `success(CardList)`, `loading`, `normal/idle`, `empty`?

2019-03-13 20:02 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/View/CardListView.swift
> +        switch searchStatus {
É estranho ter dois métodos de set de status. A mesma tela tem vários estados mas o estado dela é uma só. Ter dois enums para dois estados é um code smell. Sugiro ficar tudo em um estado só. 

No comentário de cima vc pode adicionar os estados de search.

2019-03-13 20:02 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/View/CardListViewController.swift
>      let screen = CardListView()
Bom, isso eu tinha deixado passar.

É estranho vc ter a viewController e a view. Ou vc usa a sua `ViewController` como view ou a sua viewController passar ser inutil e apenas uma classe para repassar ações. Basicamente ela n faz nada. Ela não abstrai regra de negócio e nem é view, apenas repassa a informação para a view. Esse design de arquitetura não ficou muito bom.

2019-03-13 20:02 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/View/CardListViewController.swift
>      var presenter: CardListPresenter!
Forced unwrap.

2019-03-13 20:20 UTC, cs-andre-faruolo commented on magicbyirineu/Modules/CardList/View/CardListViewController.swift
>      let screen = CardListView()
Então cara, seguimos esse design de arquitetura baseado naquelas video-aulas do Lioy de View Coding. Estamos usando dessa forma desde o começo do Bootcamp. Acho que vale o feedback, com certeza, pra projetos futuros, mas você não acha que o retrabalho de mudar isso nessa altura do campeonato é valido?

2019-03-14 00:08 UTC, cs-daniel-lima commented
![image](https://user-images.githubusercontent.com/47391973/54322482-19381580-45d4-11e9-86c4-208a2d14e711.png)

Está mostrando a mensagem da tela inicial na tela de favoritos

2019-03-14 00:09 UTC, cs-daniel-lima requested changes
![image](https://user-images.githubusercontent.com/47391973/54322511-3a006b00-45d4-11e9-93c0-26fbcc71d591.png)
Está mostrando a mensagem da tela inicial na tela de favoritos, aqui deveria dizer que o usuário ainda não tem nenhuma carta favoritada

2019-03-14 12:59 UTC, cs-joao-souza approved these changes

2019-03-14 13:05 UTC, cs-daniel-lima approved these changes

2019-03-14 13:05 UTC, merged