Feature/fetch all cards from a set
cs-daniel-lima/magicbyirineu pull request #115
Opened 2019-03-13 19:27 UTC by cs-kaique-magno

2019-03-13 20:06 UTC, cs-joao-souza requested changes

2019-03-13 20:06 UTC, cs-joao-souza commented on magicbyirineu/Managers/API/APIManager.swift
> +                    completion(Result.success(magicResponse), httpResponse?.allHeaderFields)
```suggestion
DispatchQueue.main.async {
       completion(Result.success(magicResponse), httpResponse?.allHeaderFields)
}                   
```

Como vocês estão fazendo a request usando o URLSession, se não me engano o `completion` tem de ser executado na main thread pra vc evitar que lá na frente vc tenha que mandar atualizações de UI na main thread. Em um presenter por exemplo. Todos eles, o de sucesso e o de failure.

2019-03-13 20:17 UTC, cs-kaique-magno commented on magicbyirineu/Managers/API/APIManager.swift
> +                    completion(Result.success(magicResponse), httpResponse?.allHeaderFields)
Faz sentido mesmo 👍

2019-03-13 23:43 UTC, cs-daniel-lima approved these changes

2019-03-14 16:48 UTC, cs-joao-souza approved these changes

2019-03-14 18:22 UTC, merged