Feature/feature search
cs-daniel-lima/magicbyirineu pull request #32
Opened 2019-02-20 21:56 UTC by cs-daniel-lima

Seguindo as recomendações do @cs-joao-souza aproveitei o início desta feature para refatorar algumas coisas que considero importantes para seguir em frente com a feature e seria bom já ter isso na develop para que todos possam se beneficiar.

**Principais mudanças:**
- Gemfile (bundler) garantindo versão do cocoapods
- Garantidas versões de libs no Podfile e Cartfile
- .gitattributes removido
- Todas as imagens adicionadas ao assets catalog
- Algumas classes já se encontram refatoradas seguindo as recomendações enviadas via slack (CardListView, MgicTabBarController e MagicSearchBar)

2019-02-22 11:59 UTC, cs-joao-souza requested changes

2019-02-22 11:59 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/View/CardListViewController.swift
> -        screen.searchBar.setupSearchBar()
Ainda falta chamar o super aqui.

2019-02-22 11:59 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/View/MagicSearchBar.swift
>          let textField = value(forKey: "_searchField") as! UITextField
Perigoso isso aqui. Por que não criaram seu próprio componente de busca?

2019-02-22 11:59 UTC, cs-joao-souza commented on magicbyirineu/Modules/Favorites/View/FavoritesViewController.swift
>      override func viewDidAppear(_ animated: Bool) {
Falta chamar o super.

2019-02-25 13:25 UTC, cs-daniel-lima commented on magicbyirineu/Modules/CardList/View/CardListViewController.swift
> -        screen.searchBar.setupSearchBar()
Correção submetida

2019-02-25 13:25 UTC, cs-daniel-lima commented on magicbyirineu/Modules/CardList/View/MagicSearchBar.swift
>          let textField = value(forKey: "_searchField") as! UITextField
Correção submetida

2019-02-25 13:25 UTC, cs-daniel-lima commented on magicbyirineu/Modules/Favorites/View/FavoritesViewController.swift
>      override func viewDidAppear(_ animated: Bool) {
Correção submetida

2019-02-25 13:34 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/View/CardListViewController.swift
> +        screen.searchBar.additionalSetupAfterDisplay()
o super é chamado sempre antes.

2019-02-25 13:34 UTC, cs-joao-souza approved these changes

2019-02-25 13:41 UTC, cs-kaique-magno approved these changes

2019-02-25 13:44 UTC, merged