Creates & Implements: Detail Screen modules and tests
cs-daniel-lima/magicbyirineu pull request #71
Opened 2019-02-28 19:36 UTC by cs-andre-faruolo

2019-02-28 19:49 UTC, cs-daniel-lima requested changes

2019-02-28 19:49 UTC, cs-daniel-lima commented on magicbyirineu/Modules/CardDetail/Interactor/CardDetailInteractor.swift
> +
Lembra que o @cs-joao-souza já recusou PR's por conta de classes vazias? Temos que ver com o @cs-joao-souza como podemos fazer neste caso, uma vez que é um elemento do VIPER

2019-02-28 19:49 UTC, cs-daniel-lima commented on magicbyirineu/Modules/CardDetail/View/CardDetailScreen.swift
> +
dismissButton, cardImage e backgroundImage poderiam ser let?

2019-02-28 21:28 UTC, cs-kaique-magno approved these changes

2019-02-28 21:41 UTC, cs-daniel-lima requested changes

2019-02-28 21:41 UTC, cs-daniel-lima commented on magicbyirineu/Modules/CardDetail/Interactor/CardDetailInteractor.swift
> +
Lembrar de perguntar isso na daily amanhã

2019-03-01 18:31 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardDetail/Interactor/CardDetailInteractor.swift
> +
@cs-daniel-lima Então, temos que tomar cuidado com isso. Classe vazia nunca. Arquitetura é apenas um guia. Caso a sua tela seja estática por exemplo vc n vai usar viper com presenter, iteractor e router vazios, só porque a arquitetura exige. Subiu classe vazia pra Dev, barra. Subiu apenas para a feature branch ta ok porque ainda está em desenvolvimento

2019-03-01 18:52 UTC, cs-daniel-lima approved these changes

2019-03-01 19:09 UTC, merged