Develop hot fix/card list interactor refactor
cs-daniel-lima/magicbyirineu pull request #75
Opened 2019-03-01 19:28 UTC by cs-kaique-magno

2019-03-01 20:07 UTC, cs-joao-souza submitted a review, later dismissed

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
> +        let keys = self.interactor.objectsBySet.keys.map { (set) -> CardSet in
Esse `map` aqui está sem intuito. Ele está apenas iterando pelos objetos e retornando o objeto atual. Talvez n seria um `compactMap`???

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
> +        let keys = self.interactor.objectsBySet.keys.map { (set) -> CardSet in
Mesma coisa do de cima.

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
> +                self.interactor.fetchSearchingCards(cardName: self.query!)
```suggestion
               if let query = query {
                     self.interactor.fetchSearchingCards(cardName: query)
                }
```

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
> +                self.interactor.fetchSearchingCards(cardName: self.query!)
Forced unwrap

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
> +        let keys = self.interactor.objectsBySet.keys.map { (set) -> CardSet in
Mesma coisa do map de cima.

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
> +        let object = self.interactor.objectsBySet[set]![indexPath.row]
```suggestion
        guard let object = self.interactor.objectsBySet[set]?[indexPath.row] else { return }
```

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
> +        let object = self.interactor.objectsBySet[set]![indexPath.row]
Forced unwrap

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
> +        let keys = self.interactor.objectsBySet.keys.map { (set) -> CardSet in
Mesma coisa aqui

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Modules/CardList/Presenter/CardListPresenter.swift
> +            self.interactor.fetchSearchingCards(cardName: self.query!)
Forced unwrap

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Protocols/Repository/CardSetRepository.swift
> +    func getAll(completion: @escaping (Result<[CardSet]>) -> Void)
```suggestion
    func fetchCardSet(completion: @escaping (Result<[CardSet]>) -> Void)
```

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Protocols/Repository/CardSetRepository.swift
> +    func getAll(completion: @escaping (Result<[CardSet]>) -> Void)
Apenas sugestão.

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Services/CardAPIClient.swift
> +    init() {
```suggestion
    init(apiManager: APIManager = APIManager()) {    
```

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Services/CardAPIClient.swift
> +        self.apiManager = APIManager()
```suggestion
        self.apiManager = apiManager
```

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Services/CardAPIClient.swift
> +    init() {
Dessa forma você pode injetar seu `APIManager` para testar.

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Services/CardAPIClient.swift
> +    var apiManager:APIManager
Não pode ser `let`?

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Services/CardSetAPIClient.swift
> +    var apiManager:APIManager
Não pode ser `let`?

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Services/CardSetAPIClient.swift
> +        self.apiManager = APIManager()
Mesma coisa no construtor aqui.

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Services/TypeAPIClient.swift
> +    var apiManager:APIManager
Não pode ser `let`?

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineu/Services/TypeAPIClient.swift
> +    init() {
Mesma coisa no construtor aqui

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineuTests/Modules/CardList/CardListInteractorSpec.swift
> +        let cardRepositoryMock = CardRepositoryMock()
Se você não instanciar os mocks no `beforeEach` vc pode ter problema e esquecer de alterar alguma variável de volta pois a instância compartilhada entre os métodos continuará a mesma.

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineuTests/Modules/CardList/CardListInteractorSpec.swift
> +        context("When it is initialized"){
padronizar `when` letra minúscula ou maiúscula. Discutir com o time.

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineuTests/Modules/CardList/CardListInteractorSpec.swift
> +            it("should have CardSets"){
```suggestion
            it("has CardSets count greater than zero"){
```

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineuTests/Modules/CardList/CardListInteractorSpec.swift
> +            it("the first card should have the name Forest"){
```suggestion
            it("has the first card with name Forest"){
```

2019-03-01 20:07 UTC, cs-joao-souza commented on magicbyirineuTests/Modules/CardList/CardListInteractorSpec.swift
> +            sut!.cleanAll()
Acho que esse forced unwrap é desnecessário.

2019-03-01 20:15 UTC, cs-daniel-lima requested changes

2019-03-01 20:15 UTC, cs-daniel-lima commented on magicbyirineuTests/Modules/CardList/CardListInteractorSpec.swift
> +        context("When it is initialized"){
Todos os testes já escritos estamos usando letra minúscula no início da sentença do contexto e dos it's

2019-03-06 17:36 UTC, cs-daniel-lima approved these changes

2019-03-06 18:32 UTC, cs-andre-faruolo approved these changes

2019-03-06 18:44 UTC, merged